apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: poc-second
  labels:
    app: mongo
    autopoc.io/project: second
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
