apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: poc-second
  labels:
    app: mongo
    autopoc.io/project: second
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
