apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: poc-second
  labels:
    app: worker
    autopoc.io/project: second
spec:
  type: ClusterIP
  selector:
    app: worker
  ports:
    - port: 8081
      targetPort: 8081
